# Generated by Django 5.1.3 on 2024-12-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_product_image_hover'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='details',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
