# Generated by Django 5.1.3 on 2024-12-08 12:09

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_product_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('comment', models.CharField(default='', max_length=250)),
                ('product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='personal.product')),
            ],
        ),
    ]
